### ISSUE TITLE
Collapse of text in game

### ISSUE THREAD

**Issue by Tito5e** [Wynntils/Wynntils#1690]
## Situation

I was killing mobs and suddenly the text started to collapse.
There was no screen freezing and flashing.

I don't know if this is a FabricMC issue or a Wynntils issue.
(Using DeepL Translator)

## Wynntils Version

* wynntils-0.0.3-alpha.112-fabric+MC-1.19.4

## Other Mods
<details>

* AuthMe-6.1.0
* CreativeCore-2.10.12
* fabric-api-0.84.0
* fabric-language-kotlin-1.9.6+kotlin.1.8.22
* fabric-optifine-capes-2.0.0
* FerriteCore-5.2.0
* ForceCloseLoadingScreen-2.1.0
* Iris-MC-1.6.4
* Krypton-0.2.2
* Lithium-0.11.1
* ModMenu-6.2.3
* Sodium-0.4.10+build.24
* Starlight-1.1.1+ae22326
* yet-another-config-lib-3.0.3
* Zoomify-2.9.4

</details>

## logs/latest.log
<details>

```
[15:16:05] [Render thread/WARN]: Failed to load texture: minecraft:default/0
java.io.FileNotFoundException: minecraft:default/0
	at net.minecraft.class_5912.method_43043(class_5912.java:21) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049$class_4006.method_18156(class_1049.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_18153(class_1049.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_4625(class_1049.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_24303(class_1060.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4616(class_1060.java:70) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4619(class_1060.java:120) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668$class_4683.method_23563(class_4668.java:241) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar:?]
	at net.minecraft.class_1921$class_4687.method_23595(class_1921.java:1015) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_1921.method_23012(class_1921.java:809) ~[client-intermediary.jar:?]
	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_4597$class_4598.getBuffer(class_4597.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_327$class_5232.accept(class_327.java:280) ~[client-intermediary.jar:?]
	at net.minecraft.class_5223.method_27477(class_5223.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_5223.method_27473(class_5223.java:120) ~[client-intermediary.jar:?]
	at net.minecraft.class_5223.method_27472(class_5223.java:84) ~[client-intermediary.jar:?]
	at net.minecraft.class_5223.method_27479(class_5223.java:80) ~[client-intermediary.jar:?]
	at net.minecraft.class_327.method_1724(class_327.java:341) ~[client-intermediary.jar:?]
	at net.minecraft.class_327.method_27529(class_327.java:186) ~[client-intermediary.jar:?]
	at net.minecraft.class_327.method_27522(class_327.java:125) ~[client-intermediary.jar:?]
	at com.wynntils.utils.render.buffered.BufferedFontRenderer.renderText(BufferedFontRenderer.java:162) ~[wynntils-0.0.3-alpha.112-fabric+MC-1.19.4.jar:?]
	at com.wynntils.utils.render.buffered.BufferedFontRenderer.renderText(BufferedFontRenderer.java:334) ~[wynntils-0.0.3-alpha.112-fabric+MC-1.19.4.jar:?]
	at com.wynntils.utils.render.buffered.BufferedFontRenderer.renderAlignedTextInBox(BufferedFontRenderer.java:208) ~[wynntils-0.0.3-alpha.112-fabric+MC-1.19.4.jar:?]
	at com.wynntils.utils.render.buffered.BufferedFontRenderer.renderAlignedTextInBox(BufferedFontRenderer.java:262) ~[wynntils-0.0.3-alpha.112-fabric+MC-1.19.4.jar:?]
	at com.wynntils.features.overlays.GameBarsOverlayFeature$BaseBarOverlay.renderText(GameBarsOverlayFeature.java:198) ~[wynntils-0.0.3-alpha.112-fabric+MC-1.19.4.jar:?]
	at com.wynntils.features.overlays.GameBarsOverlayFeature$BaseBarOverlay.render(GameBarsOverlayFeature.java:155) ~[wynntils-0.0.3-alpha.112-fabric+MC-1.19.4.jar:?]
	at com.wynntils.core.features.overlays.OverlayManager.renderOverlays(OverlayManager.java:250) ~[wynntils-0.0.3-alpha.112-fabric+MC-1.19.4.jar:?]
	at com.wynntils.core.features.overlays.OverlayManager.onRenderPre(OverlayManager.java:204) ~[wynntils-0.0.3-alpha.112-fabric+MC-1.19.4.jar:?]
	at com.wynntils.core.features.overlays.__OverlayManager_onRenderPre_Pre.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[net_minecraftforge_eventbus-6.0.4-2a64588f677c3575.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[net_minecraftforge_eventbus-6.0.4-2a64588f677c3575.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[net_minecraftforge_eventbus-6.0.4-2a64588f677c3575.jar:?]
	at com.wynntils.core.WynntilsMod.postEvent(WynntilsMod.java:69) ~[wynntils-0.0.3-alpha.112-fabric+MC-1.19.4.jar:?]
	at com.wynntils.core.events.MixinHelper.post(MixinHelper.java:21) ~[wynntils-0.0.3-alpha.112-fabric+MC-1.19.4.jar:?]
	at net.minecraft.class_329.wrapOperation$bni000$wynntils$onRenderFood(class_329.java:2986) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1760(class_329.java:845) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:216) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:918) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1218) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[fabric-loader-0.14.21-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
```

</details>

## Screenshots
![2023-07-06_15 16 56](https://github.com/Wynntils/Artemis/assets/72246321/c480c635-23bf-4b35-bcd9-e2b0376145b8)
![2023-07-06_15 16 53](https://github.com/Wynntils/Artemis/assets/72246321/f5c72c25-2486-437a-8f2a-f916bf54d839)
![2023-07-06_15 35 08](https://github.com/Wynntils/Artemis/assets/72246321/7dadeb81-70ba-4b2c-9ff3-db8ab44fb734)

**Comment by magicus** [comment]
Log says "Failed to load texture: minecraft:default/0". This is not a Wynntils problem.
