### ISSUE TITLE
[2.0.3] Overlay crashes due to possibly wrong parsing

### ISSUE THREAD

**Issue by kristofbolyai** [Wynntils/Wynntils#1735]
```
Crashed overlay: com.wynntils.features.overlays.ContentTrackerOverlayFeature$ContentTrackerOverlay
java.lang.NullPointerException: Cannot invoke "com.wynntils.models.content.type.ContentType.getDisplayName()" because the return value of "com.wynntils.models.content.ContentModel.getTrackedType()" is null
	at com.wynntils.features.overlays.ContentTrackerOverlayFeature$ContentTrackerOverlay.render(ContentTrackerOverlayFeature.java:136)
	at com.wynntils.core.features.overlays.OverlayManager.renderOverlays(OverlayManager.java:250)
	at com.wynntils.core.features.overlays.OverlayManager.onRenderPost(OverlayManager.java:211)
	at com.wynntils.core.features.overlays.__OverlayManager_onRenderPost_Post.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at com.wynntils.core.WynntilsMod.postEvent(WynntilsMod.java:69)
	at com.wynntils.core.events.MixinHelper.post(MixinHelper.java:21)
	at net.minecraft.class_329.handler$dfc000$wynntils$onRenderGuiPost(class_329.java:6969)
	at net.minecraft.class_329.method_1753(class_329.java:374)
	at net.minecraft.class_757.method_3192(class_757.java:918)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by magicus** [comment]
Fixed by https://github.com/Wynntils/Artemis/pull/1747. (But a nicer solution would be good to have)
