### ISSUE TITLE
Class Selection screen crashes when using KaiMyEntity 

### ISSUE THREAD

**Issue by EnderNon** [Wynntils/Wynntils#2202]
kaimyentity is a mod that lets you use mmd models for your player character. If you do use the mod though, Artemis' /class menu completely crashes and does not load.

What version of the mod are you using? Please include a full version number. r400 on 1.19, though this issue definitely applies to later versions. I know this because a friend on 1.20 has this issue.
What mod loader did you use? Fabric
Did you use any other mods? Only Kaimyentity is of importance 
What operating system are you using? Windows
What did you do? login to wynncraft 
What did you expect to see? The class Selection menu 
What did you see instead? a message in chat that said that the class Selection screen was forcefully closed

**Comment by magicus** [comment]
Can you please post the part of the log from when the crash happens?

**Comment by magicus** [comment]
Question: I assume you are using the Artemis special character selection menu, right? A workaround would be to disable it. I cannot guarantee that we can fix mod interop issues, but we might have a look at it. A stacktrace would help.

**Comment by EnderNon** [comment]
[kaimyentity wynntils crash.txt](https://github.com/Wynntils/Artemis/files/13060511/kaimyentity.wynntils.crash.txt)
here is my log if that's what you mean

**Comment by magicus** [comment]
Here's the relevant part:

```
[11:52:51] [Render thread/WARN]: Disabling screen CharacterSelectorScreen due to render
[11:52:51] [Render thread/ERROR]: Exception thrown by com.wynntils.screens.characterselector.CharacterSelectorScreen
net.minecraft.class_148: Rendering entity in world
	at net.minecraft.class_898.method_3954(class_898.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_29977(class_490.java:166) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1188) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_48472(class_490.java:166) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_2486(class_490.java:133) ~[client-intermediary.jar:?]
	at com.wynntils.screens.characterselector.CharacterSelectorScreen.renderPlayer(CharacterSelectorScreen.java:405) ~[wynntils-0.0.3-alpha.370-fabric+MC-1.19.4.jar:?]
	at com.wynntils.screens.characterselector.CharacterSelectorScreen.doRender(CharacterSelectorScreen.java:170) ~[wynntils-0.0.3-alpha.370-fabric+MC-1.19.4.jar:?]

[...]
Caused by: java.lang.ClassCastException: class com.wynntils.screens.characterselector.CharacterSelectorScreen cannot be cast to class net.minecraft.class_490 (com.wynntils.screens.characterselector.CharacterSelectorScreen and net.minecraft.class_490 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3c0f93f1)
	at net.minecraft.class_1007.handler$bmm000$kaimyentity$render(class_1007.java:2165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1007.method_4215(class_1007.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1007.method_3936(class_1007.java:43) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:141) ~[client-intermediary.jar:?]
	... 24 more
[11:52:51] [Render thread/WARN]: Chat error message sent: Wynntils error: Screen 'CharacterSelectorScreen' has crashed in render
```

**Comment by magicus** [comment]
net/minecraft/class_490 seem to be net/minecraft/client/gui/screen/ingame/InventoryScreen.

I'm guessing that KaiMyEntity assumes that a player being rendered in a screen will only happen in the inventory. Not sure if we can do anything about it.

**Comment by magicus** [comment]
I think the problematic line in KAIMyEntity is here:

https://github.com/Gengorou-C/KAIMyEntity-C/blob/83b4f45268adc7a92f62ee3bac7fa0c91442e6b0/src/main/java/com/kAIS/KAIMyEntity/mixin/KAIMyEntityPlayerRendererMixin.java#L165

You should probably file a bug on them, asking them to do a type check before casting.

**Comment by kristofbolyai** [comment]
Most likely a wontfix.
