### ISSUE TITLE
MalformedJsonException + error 'Signature is missing from Property textures' spamming in the console

### ISSUE THREAD

**Issue by Aeldit** [Wynntils/Wynntils#2560]
## The errors
There are multiple errors like this that appear :
```log
[10:22:10] [ForkJoinPool.commonPool-worker-5/WARN]: Failure in net manager [handleJsonObject], processing API:API_ATHENA_USER_INFO
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8 path $
	at com.google.gson.JsonParser.parseReader(JsonParser.java:76) ~[gson-2.10.1.jar:?]
	at com.wynntils.core.net.NetResult.lambda$handleJsonObject$2(NetResult.java:57) ~[wynntils-1.2.19-fabric+MC-1.20.2.jar:?]
	at com.wynntils.core.net.NetResult.lambda$handleReader$1(NetResult.java:46) ~[wynntils-1.2.19-fabric+MC-1.20.2.jar:?]
	at com.wynntils.core.net.NetResult.lambda$wrappingHandler$5(NetResult.java:111) ~[wynntils-1.2.19-fabric+MC-1.20.2.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:844) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1465) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.1.jar:?]
	at com.google.gson.JsonParser.parseReader(JsonParser.java:71) ~[gson-2.10.1.jar:?]
	... 13 more
```

This error happens approximately 10 times when playing for 20 minutes.

In the provided log, this error occurs only once (over the span of a minute) and is located at line 203

There is also this error
```log
[10:22:04] [Worker-Main-12/ERROR]: Signature is missing from Property textures
```
that appears a lot (most of the time it appears multiple times in a row).

In the provided log, this error appears 28 and first occurs at line 193

## Versions

Wynntils 1.2.19
Fabric API 0.91.6+1.20.2
Fabric Loader 0.15.11
Minecraft 1.20.2

## Logs
[latest.log](https://github.com/user-attachments/files/15580896/latest.log)

**Comment by kristofbolyai** [comment]
The signature stuff is an interaction of Wynn and Minecraft texture signing. Not a problem.

The JSON exceptions is our servers being a bit wonky lately. Do you have any other issues? If not, I'll close this issue, as neither of this is something we directly need to/can fix.

**Comment by Aeldit** [comment]
I don't have any other issue so I'll close this then

**Comment by magicus** [comment]
@kristofbolyai Maybe we should catch the exception and write something more useful to the console when it happens. It's not the first time Athena is acting up...

**Comment by kristofbolyai** [comment]
> @kristofbolyai Maybe we should catch the exception and write something more useful to the console when it happens. It's not the first time Athena is acting up...

I guess. If I ever come close to fixing that, time wise.
